### ISSUE TITLE
getData() fails for 'new' empty Word doc

### ISSUE THREAD

**Issue by augustjanse** [TorkelV/officeprops#1]
1. Right click -> New -> Microsoft Word document
2. Read into `file` and `await OFFICEPROPS.getData(file);`
3. Throws: `Error: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?`

If I open the Word file, enter `a` and save, this works.

**Comment by TorkelV** [comment]
Which file format? .docx?

Not sure if I'll find the time to fix this any time soon.
If you want to fix it yourself, I'd be happy to merge a PR 👍

**Comment by augustjanse** [comment]
Yeah, `.docx`. This actually doesn't happen if I create an empty file in Word and save it. Not sure how Windows creates the file from File Explorer.

Windows 10 Pro on Insider Build 21376. Word version 2104.

Thanks, but I probably won't have time to fix it either. It's no major issue for me, just wanted to report it. Cool library!

**Comment by TorkelV** [comment]
Thanks for the report, I figured out the issue, but not sure it's worth fixing.

When you create an office file file from file explorer it creates an empty file with the corresponding extension. 
So when you create a word file you get an empty(0b) file with a .docx extension, and it won't be a valid .docx file untill it is saved through an office app.

The library throws an error if the file is not valid, which is technically correct for an empty file with a .docx extension.
Could change the error to say that the file is not valid instead of assuming it's corrupted though.

**Comment by augustjanse** [comment]
Oh, you're right. My bad, thanks for troubleshooting for me!
